### ISSUE TITLE
Reference to parameters not supported when generating model from swagger 2.0 json definition

### ISSUE THREAD

**Issue by arno-di-loreto** [strongloop/loopback-swagger#10]
When generating a model based on a Swagger 2.0 json definition containing parameters reference (with _slc loopback:swagger_, there's an error when running _slc run ._.
This error is due the lack of resourceId attribute which is not handled correctly when defined via a parameters reference.
There is no problem with the same API definition when parameters are defined inline.

Steps in project directory:
- slc loopback
- slc loopback:swagger
  - choosing json file
- slc run .

Error when running slc run . on project build from swagger definition with parameters reference:

``` bash
APIHandyman:simple_with_parameters_ref apihandyman$ slc run .
INFO strong-agent v2.0.1 profiling app 'simple_with_parameters_ref' pid '40414'
INFO strong-agent[40414] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)
/Users/apihandyman/Strongloop/simple_with_parameters_ref/server/models/swagger-api.js:45
SwaggerApi.getItem = function(, callback) {
                              ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at Module.module.__proto__.require (/usr/local/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-agent/lib/agent.js:185:42)
    at require (module.js:384:17)
    at /Users/arnaud/CloudStation/Strongloop/simple_with_parameters_ref/node_modules/loopback-boot/lib/executor.js:217:20
    at Array.forEach (native)
```

Definition without parameters reference for _resourceId_ on path */resources/{resourceId}:

``` YAML
swagger: '2.0'
info:
  version: 0.0.1
  title: Simple API
produces:
  - application/json
consumes:
  - application/json
paths:
  /resources:
    get:
      operationId: getResources
      responses:
        '200':
          description: The available resources
          schema:
            type: array
            items:
              $ref: '#/definitions/resource'
    post:
      operationId: addResource
      parameters:
        - name: resource
          in: body
          schema:
            $ref: '#/definitions/resource'
      responses:
        '201':
          description: The resource has been created
  '/resources/{resourceId}':
    get:
      summary: Gets an item
      description: Gets an item
      operationId: getItem
      parameters:
        - name: resourceId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: The item
          schema:
            $ref: '#/definitions/resource'
        '404':
          description: The resource do not exists
    delete:
      operationId: deleteResource
      parameters:
        - name: resourceId
          in: path
          type: string
          required: true
      responses:
        '204':
          description: The resource has been deleted
        '404':
          description: The resource do not exists
definitions:
  resource:
    properties:
      resourceId:
        type: string
        example: 49d15f19-9175-49b5-8454-3e0e815b2303
      name:
        type: string
        description: "the resource's name"
        example: maurice
```

Definition with parameters reference for _resourceId_ on path */resources/{resourceId}:

``` YAML
swagger: "2.0"

info:
  version: 0.0.1
  title: Simple API

produces:
  - application/json

consumes:
  - application/json

parameters:
  resourceId:
    name: resourceId
    in: path
    type: string
    required: true 

paths:
  /resources:
    get:
      operationId: getResources
      responses:
        200:
          description: The available resources
          schema:
            type: array
            items:
              $ref: "#/definitions/resource"
    post:
      operationId: addResource
      parameters:
        - name: resource
          in: body
          schema:
            $ref: "#/definitions/resource"
      responses:
        201:
          description: The resource has been created
  /resources/{resourceId}:
    get:
      summary: Gets an item
      description: Gets an item
      operationId: getItem
      parameters:
        - $ref: "#/parameters/resourceId"
      responses:
        200:
          description: The item
          schema:
            $ref: "#/definitions/resource"
        404:
          description: The resource do not exists

    delete:
      operationId: deleteResource
      parameters:
        - $ref: "#/parameters/resourceId"
      responses:
        204:
          description: The resource has been deleted
        404:
          description: The resource do not exists

definitions:
  resource:
    properties:
      resourceId:
        type: string
        example: 49d15f19-9175-49b5-8454-3e0e815b2303
      name: 
        type: string
        description: the resource's name
        example: maurice
```

**Comment by 0candy** [comment]
Could you please provide the json file that you had trouble with?

**Comment by arno-di-loreto** [comment]
As I've declared this a long time ago, I've just tested it again with a fresh loopback installation. The bug is still here.
```
slc --version
strongloop v6.0.0 (node v5.1.0)
├── strong-arc@1.8.5 (d01942e)
├── strong-build@2.1.0 (47dd24a)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.1.0 (eb2f788)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```
Here's the JSON file.
```JSON
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.1",
        "title": "Simple API"
    },
    "produces": [
        "application/json"
    ],
    "consumes": [
        "application/json"
    ],
    "parameters": {
        "resourceId": {
            "name": "resourceId",
            "in": "path",
            "type": "string",
            "required": true
        }
    },
    "paths": {
        "/resources": {
            "get": {
                "operationId": "getResources",
                "responses": {
                    "200": {
                        "description": "The available resources",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resource"
                            }
                        }
                    }
                }
            },
            "post": {
                "operationId": "addResource",
                "parameters": [
                    {
                        "name": "resource",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/resource"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The resource has been created"
                    }
                }
            }
        },
        "/resources/{resourceId}": {
            "get": {
                "summary": "Gets an item",
                "description": "Gets an item",
                "operationId": "getItem",
                "parameters": [
                    {
                        "$ref": "#/parameters/resourceId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The item",
                        "schema": {
                            "$ref": "#/definitions/resource"
                        }
                    },
                    "404": {
                        "description": "The resource do not exists"
                    }
                }
            },
            "delete": {
                "operationId": "deleteResource",
                "parameters": [
                    {
                        "$ref": "#/parameters/resourceId"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "The resource has been deleted"
                    },
                    "404": {
                        "description": "The resource do not exists"
                    }
                }
            }
        }
    },
    "definitions": {
        "resource": {
            "properties": {
                "resourceId": {
                    "type": "string",
                    "example": "49d15f19-9175-49b5-8454-3e0e815b2303"
                },
                "name": {
                    "type": "string",
                    "description": "the resource's name",
                    "example": "maurice"
                }
            }
        }
    }
}
```

**Comment by roberto-paes** [comment]
One year old very basic bug :-1:

**Comment by roytan883** [comment]
@superkhau @0candy 
yes, i just use loopback swagger, still have this problem.
**$ref is very basic feature of swagger, sadly loopback swagger not support it.**

**Comment by bajtos** [comment]
Closing as stale.
